/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import Db_conncection.DB;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author madur
 */
public final class calculate_bill extends javax.swing.JFrame {

    /**
     * Creates new form add_new_job
     */
    
        DB obj=new DB();
        Connection con=obj.connect();
        
    public calculate_bill() {
        initComponents();
       
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        catergory = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        duration = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        space = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        dur = new javax.swing.JLabel();
        bill_duration = new javax.swing.JTextField();
        spac = new javax.swing.JLabel();
        bill_space = new javax.swing.JTextField();
        quan = new javax.swing.JLabel();
        bill_quantity = new javax.swing.JTextField();
        toat = new javax.swing.JLabel();
        bill_total = new javax.swing.JTextField();
        head2 = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculate Bill");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/warehouse.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setPreferredSize(new java.awt.Dimension(475, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.gray);
        jLabel2.setText("User No.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        no.setBackground(java.awt.Color.lightGray);
        no.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        no.setForeground(java.awt.Color.white);
        no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        no.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        no.setOpaque(false);
        no.setPreferredSize(new java.awt.Dimension(2, 21));
        no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noKeyReleased(evt);
            }
        });
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 120, -1));

        catergory.setEditable(false);
        catergory.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        catergory.setForeground(new java.awt.Color(255, 255, 255));
        catergory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        catergory.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        catergory.setOpaque(false);
        catergory.setPreferredSize(new java.awt.Dimension(2, 21));
        jPanel1.add(catergory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.gray);
        jLabel4.setText("Duration");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        duration.setEditable(false);
        duration.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        duration.setForeground(new java.awt.Color(255, 255, 255));
        duration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        duration.setOpaque(false);
        duration.setPreferredSize(new java.awt.Dimension(2, 21));
        duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationActionPerformed(evt);
            }
        });
        jPanel1.add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.gray);
        jLabel5.setText("Space");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        space.setEditable(false);
        space.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        space.setForeground(new java.awt.Color(255, 255, 255));
        space.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        space.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        space.setOpaque(false);
        space.setPreferredSize(new java.awt.Dimension(2, 21));
        space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceActionPerformed(evt);
            }
        });
        jPanel1.add(space, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 120, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.gray);
        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        quantity.setEditable(false);
        quantity.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        quantity.setForeground(new java.awt.Color(255, 255, 255));
        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        quantity.setOpaque(false);
        quantity.setPreferredSize(new java.awt.Dimension(2, 21));
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 120, -1));

        lbl_name.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_name.setForeground(java.awt.Color.orange);
        jPanel1.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 120, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(java.awt.Color.lightGray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculate Bill");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 20, 590, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.gray);
        jLabel8.setText("Catergory");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        back.setBackground(java.awt.Color.lightGray);
        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setForeground(java.awt.Color.darkGray);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_1.png"))); // NOI18N
        back.setText("  Back");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.setOpaque(false);

        dur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dur.setForeground(java.awt.Color.gray);

        bill_duration.setEditable(false);
        bill_duration.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bill_duration.setForeground(new java.awt.Color(255, 255, 255));
        bill_duration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bill_duration.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.lightGray));
        bill_duration.setOpaque(false);

        spac.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        spac.setForeground(java.awt.Color.gray);

        bill_space.setEditable(false);
        bill_space.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bill_space.setForeground(new java.awt.Color(255, 255, 255));
        bill_space.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bill_space.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.lightGray));
        bill_space.setOpaque(false);

        quan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        quan.setForeground(java.awt.Color.gray);

        bill_quantity.setEditable(false);
        bill_quantity.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bill_quantity.setForeground(new java.awt.Color(255, 255, 255));
        bill_quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bill_quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.lightGray));
        bill_quantity.setOpaque(false);

        toat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        toat.setForeground(java.awt.Color.gray);
        toat.setPreferredSize(new java.awt.Dimension(35, 17));

        bill_total.setEditable(false);
        bill_total.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bill_total.setForeground(java.awt.Color.orange);
        bill_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bill_total.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.lightGray));
        bill_total.setOpaque(false);

        head2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        head2.setForeground(java.awt.Color.lightGray);
        head2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        head.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        head.setForeground(java.awt.Color.lightGray);
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(head2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bill_total, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bill_space, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bill_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bill_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(head2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dur)
                    .addComponent(bill_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bill_space, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spac, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bill_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bill_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 230, 240));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 640, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(612, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKeyReleased
        // TODO add your handling code here:
       //search job
            try {
                String str = no.getText();
                
                PreparedStatement st = con.prepareStatement("select * from add_job where id=?");
                st.setString(1, str);
                //Excuting Query
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    //Sets Records in TextFields.
                    no.setText(rs.getString(1));
                    catergory.setText(rs.getString(2));
                    duration.setText(rs.getString(3));
                    space.setText(rs.getString(4));
                    quantity.setText(rs.getString(5));
                    no.requestFocus();
                } else {
                 //clear the text
                 catergory.setText("");
                 duration.setText("");
                 space.setText("");
                 quantity.setText("");
                 
                 //clear bill text
                 head.setText("");
                 head2.setText("");
                 dur.setText("");
                 spac.setText("");
                 quan.setText("");
                 toat.setText("");
                 bill_total.setText("");
                 bill_quantity.setText("");
                 bill_space.setText("");
                 bill_duration.setText("");
                 
                }
                //Create Exception Handler
            } catch (HeadlessException | SQLException ex) {
                System.out.println(ex);
            
        }
            // end of search job
         
            
        //Calculate Bill    
        
        // Abstract class
         abstract class Selected{
         // Abstract method (does not have a body)
         public abstract void selectItem();
       }
       
       // Subclass (inherit from Select)
         class catergories extends Selected{
            @Override
            public void selectItem(){
               int day;
               int space1;
               int qt;
               day = Integer.parseInt(duration.getText());
               space1 = Integer.parseInt(space.getText());
               qt = Integer.parseInt(quantity.getText());
                        // calculate
                       //duration     
                       if(day<=10){
                       bill_duration.setText(""+day*30);
                       }
                       else if(day<=20){
                       bill_duration.setText(""+day*50);
                       }
                       else if(day<=30){
                       bill_duration.setText(""+day*70);
                       }
                       else if(day==45){
                       bill_duration.setText(""+day*100);
                       }
                       else if(day==60){
                       bill_duration.setText(""+day*120);
                       }
                       else if(day==75){
                       bill_duration.setText(""+day*150);
                       }
                       else if(day==90){
                       bill_duration.setText(""+day*150);
                       }
                       //space
                       if(space1==10){
                            bill_space.setText(""+space1*50);
                       }
                       else if(space1==20){
                       bill_space.setText(""+space1*100);
                       }
                       else if(space1==30){
                       bill_space.setText(""+space1*150);
                       }
                       else if(space1==40){
                       bill_space.setText(""+space1*200);
                       }
                       else if(space1==50){
                       bill_space.setText(""+space1*250);
                       }
                       else if(space1==60){
                       bill_space.setText(""+space1*300);
                       }
                       else if(space1==70){
                       bill_space.setText(""+space1*350);
                       }
                       else if(space1==80){
                       bill_space.setText(""+space1*400);
                       }
                       else if(space1==90){
                       bill_space.setText(""+space1*450);
                       }
                       else if(space1==100){
                       bill_space.setText(""+space1*500);
                       } 
                       //quantity
                       if(qt==10){
                       bill_quantity.setText(""+qt*10);
                       }
                       else if(qt==50){
                       bill_quantity.setText(""+qt*50);
                       }
                       else if(qt==100){
                       bill_quantity.setText(""+qt*100);
                       }
                       else if(qt==150){
                       bill_quantity.setText(""+qt*150);
                       }
                       else if(qt==200){
                       bill_quantity.setText(""+qt*200);
                       }
                       else if(qt==250){
                       bill_quantity.setText(""+qt*250);
                       }
                        
                       
        //total calculate
        day = Integer.parseInt(bill_duration.getText());
        space1 = Integer.parseInt(bill_space.getText());
        qt = Integer.parseInt(bill_quantity.getText());
        int tot = day+space1+qt;
        
        bill_total.setText(""+tot);
            }
       }
        
       Selected s1 = new catergories();
       s1.selectItem();
 
       //display bill
       head.setText("+++ Smart Ware House +++");
       head2.setText("Calculate Bill");
       dur.setText("Duration Cost :");
       spac.setText("Space Cost :");
       quan.setText("Quantity Cost :");
       toat.setText("Total :");
       // end of calculate bill 
    }//GEN-LAST:event_noKeyReleased

    private void durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationActionPerformed

    private void spaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        //add database code
           int opt =JOptionPane.showConfirmDialog(null, "Do you want to save this?","Save Database",JOptionPane.YES_NO_OPTION);
            if(opt== 0){
       try {
                // TODO add your handling code here:
                PreparedStatement pst = con.prepareStatement("insert into calculate_bill values(?,?,?,?,?,?)");
                pst.setString(1, no.getText());
                pst.setString(2, catergory.getText());
                pst.setString(3, bill_duration.getText());
                pst.setString(4, bill_space.getText());
                pst.setString(5, bill_quantity.getText());
                pst.setString(6, bill_total.getText());

                pst.executeUpdate();
                //redirects main page
                operator_main_page L1 =new operator_main_page();
                L1.setVisible(true);
                this.dispose();                
            } catch (SQLException ex) {
                Logger.getLogger(autoIn.class.getName()).log(Level.SEVERE, null, ex);
            }}else{
                operator_main_page L1 =new operator_main_page();
                L1.setVisible(true);
                this.dispose();
            }
       // end of add database code 
    }//GEN-LAST:event_backActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new calculate_bill().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField bill_duration;
    private javax.swing.JTextField bill_quantity;
    private javax.swing.JTextField bill_space;
    private javax.swing.JTextField bill_total;
    private javax.swing.JTextField catergory;
    private javax.swing.JLabel dur;
    private javax.swing.JTextField duration;
    private javax.swing.JLabel head;
    private javax.swing.JLabel head2;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField no;
    private javax.swing.JLabel quan;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel spac;
    private javax.swing.JTextField space;
    private javax.swing.JLabel toat;
    // End of variables declaration//GEN-END:variables
}
