/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import Db_conncection.DB;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author madur
 */
public class close_job extends javax.swing.JFrame {

     DB obj=new DB();
     Connection con=obj.connect();

    /**
     * Creates new form close_job
     */
    public close_job() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        catergory = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        space = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Close Existing Storage Job");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/warehouse.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(java.awt.Color.lightGray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Close Existing Storage Job");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 26, 470, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.gray);
        jLabel4.setText("Duration");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        no.setBackground(java.awt.Color.lightGray);
        no.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        no.setForeground(java.awt.Color.white);
        no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        no.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        no.setOpaque(false);
        no.setPreferredSize(new java.awt.Dimension(2, 21));
        no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noKeyReleased(evt);
            }
        });
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 120, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.gray);
        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.gray);
        jLabel5.setText("Space");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.gray);
        jLabel3.setText("Catergory");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.gray);
        jLabel2.setText("User No.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        catergory.setEditable(false);
        catergory.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        catergory.setForeground(new java.awt.Color(255, 255, 255));
        catergory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        catergory.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        catergory.setOpaque(false);
        catergory.setPreferredSize(new java.awt.Dimension(2, 21));
        jPanel1.add(catergory, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 120, -1));

        duration.setEditable(false);
        duration.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        duration.setForeground(new java.awt.Color(255, 255, 255));
        duration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duration.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        duration.setOpaque(false);
        duration.setPreferredSize(new java.awt.Dimension(2, 21));
        duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationActionPerformed(evt);
            }
        });
        jPanel1.add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 120, -1));

        space.setEditable(false);
        space.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        space.setForeground(new java.awt.Color(255, 255, 255));
        space.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        space.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        space.setOpaque(false);
        space.setPreferredSize(new java.awt.Dimension(2, 21));
        space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceActionPerformed(evt);
            }
        });
        jPanel1.add(space, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 120, -1));

        quantity.setEditable(false);
        quantity.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        quantity.setForeground(new java.awt.Color(255, 255, 255));
        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        quantity.setOpaque(false);
        quantity.setPreferredSize(new java.awt.Dimension(2, 21));
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 120, -1));

        delete.setBackground(java.awt.Color.lightGray);
        delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delete.setForeground(java.awt.Color.darkGray);
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        delete.setText(" Delete");
        delete.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        delete.setPreferredSize(new java.awt.Dimension(100, 30));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jButton3.setBackground(java.awt.Color.lightGray);
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(java.awt.Color.darkGray);
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_1.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        lbl_name.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_name.setForeground(java.awt.Color.orange);
        jPanel1.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, 20));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        back.setText("jLabel7");
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(491, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationActionPerformed

    private void spaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        operator_main_page L1 =new operator_main_page();
        L1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
               // TODO add your handling code here:
        if(no.getText().trim().isEmpty() ){
             lbl_name.setText("Needed Number.");
        }else{
             int opt =JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this job?","Delete",
                     JOptionPane.YES_NO_OPTION);
            if(opt== 0){
               try {  
                
            String str = no.getText();  
          
            PreparedStatement st = con.prepareStatement("DELETE FROM `add_job` WHERE id=?");  
            st.setString(1, str); 
            JOptionPane.showMessageDialog(this,"Job has been successfully deleted.");
            //Excuting Query  
                int rs = st.executeUpdate();
               
                no.setText("");
                catergory.setText("");
                duration.setText("");
                space.setText("");
                quantity.setText("");
                no.requestFocus();
            //Create Exception Handler  
        } catch (HeadlessException | SQLException ex) {  
            System.out.println(ex);  
        } } }
    }//GEN-LAST:event_deleteActionPerformed

    private void noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKeyReleased
        // TODO add your handling code here:
        lbl_name.setText("");
        try {  
            String str = no.getText();  
            PreparedStatement st = con.prepareStatement("select * from add_job where id=?");  
            st.setString(1, str);  
            //Excuting Query  
            ResultSet rs = st.executeQuery();  
            if (rs.next()) {   
                //Sets Records in TextFields.  
                no.setText(rs.getString(1));
                catergory.setText(rs.getString(2));  
                duration.setText(rs.getString(3));  
                space.setText(rs.getString(4));  
                quantity.setText(rs.getString(5));
                no.requestFocus();
            } else {  
                 catergory.setText("");
                 duration.setText("");
                 space.setText("");
                 quantity.setText(""); 
            }  
            //Create Exception Handler  
        } catch (HeadlessException | SQLException ex) {  
            System.out.println(ex);  
        }
        
    }//GEN-LAST:event_noKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(close_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(close_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(close_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(close_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new close_job().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTextField catergory;
    private javax.swing.JButton delete;
    private javax.swing.JTextField duration;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField no;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField space;
    // End of variables declaration//GEN-END:variables

    private void Referesh() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
