/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import Db_conncection.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author madur
 */
public final class manager_register_user extends javax.swing.JFrame {

    /**
     * Creates new form add_new_job
     */
    
    DB obj=new DB();
    Connection con=obj.connect();
                
     Register R1 = new Register();
     
    public manager_register_user() {
        initComponents();
        autoID();
        R1.setName(""+txtname);
        R1.setEmail(""+txtmail);
        R1.setNic(""+txtnic);
        R1.setPhone(""+txtphone);
        R1.setAddress(""+txtadd);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        lbl_nic = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_add = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Stotrage Job");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/warehouse.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(475, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(java.awt.Color.lightGray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register User's");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 20, 450, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.gray);
        jLabel2.setText("User No.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.gray);
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.gray);
        jLabel4.setText("E-Mail");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.gray);
        jLabel5.setText("NIC");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.gray);
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txtadd.setBackground(java.awt.Color.lightGray);
        txtadd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtadd.setForeground(new java.awt.Color(255, 255, 255));
        txtadd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtadd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        txtadd.setOpaque(false);
        txtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddActionPerformed(evt);
            }
        });
        txtadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaddKeyReleased(evt);
            }
        });
        jPanel1.add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 130, -1));

        add.setBackground(java.awt.Color.lightGray);
        add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add.setForeground(java.awt.Color.darkGray);
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        add.setText(" Reigster");
        add.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 110, 30));

        back.setBackground(java.awt.Color.lightGray);
        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setForeground(java.awt.Color.darkGray);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_1.png"))); // NOI18N
        back.setText("  Back");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 90, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.gray);
        jLabel7.setText("Phone No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtphone.setBackground(java.awt.Color.lightGray);
        txtphone.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(255, 255, 255));
        txtphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        txtphone.setOpaque(false);
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtphoneKeyReleased(evt);
            }
        });
        jPanel1.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 130, -1));

        txtnic.setBackground(java.awt.Color.lightGray);
        txtnic.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtnic.setForeground(new java.awt.Color(255, 255, 255));
        txtnic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnic.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        txtnic.setOpaque(false);
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });
        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnicKeyReleased(evt);
            }
        });
        jPanel1.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 130, -1));

        txtmail.setBackground(java.awt.Color.lightGray);
        txtmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtmail.setForeground(new java.awt.Color(255, 255, 255));
        txtmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        txtmail.setOpaque(false);
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });
        txtmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, -1));

        txtname.setBackground(java.awt.Color.lightGray);
        txtname.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        txtname.setOpaque(false);
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 130, -1));

        txtno.setEditable(false);
        txtno.setBackground(java.awt.Color.lightGray);
        txtno.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtno.setForeground(new java.awt.Color(255, 255, 255));
        txtno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.lightGray));
        txtno.setOpaque(false);
        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        txtno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnoKeyReleased(evt);
            }
        });
        jPanel1.add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, -1));

        lbl_name.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_name.setForeground(java.awt.Color.orange);
        lbl_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_nameKeyReleased(evt);
            }
        });
        jPanel1.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 110, 20));

        lbl_mail.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_mail.setForeground(java.awt.Color.orange);
        jPanel1.add(lbl_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 110, 20));

        lbl_nic.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_nic.setForeground(java.awt.Color.orange);
        jPanel1.add(lbl_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 110, 20));

        lbl_phone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_phone.setForeground(java.awt.Color.orange);
        jPanel1.add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 110, 20));

        lbl_add.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_add.setForeground(java.awt.Color.orange);
        jPanel1.add(lbl_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 110, 20));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        img.setText("jLabel8");
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(466, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         if(txtname.getText().trim().isEmpty() && txtmail.getText().trim().isEmpty() && txtnic.getText().trim().isEmpty() && txtphone.getText().trim().isEmpty() && txtadd.getText().trim().isEmpty() ){
        lbl_name.setText("Needed Name.");
        lbl_mail.setText("Needed E-Mail.");
        lbl_nic.setText("Needed NIC.");
        lbl_phone.setText("Needed Phone No.");
        lbl_add.setText("Needed Address.");
        }
        else if(txtname.getText().trim().isEmpty()){
             lbl_name.setText("Needed Name.");
        }
        else if(txtmail.getText().trim().isEmpty()){
            lbl_mail.setText("Needed E-Mail.");
        }
        else if(txtnic.getText().trim().isEmpty()){
            lbl_nic.setText("Needed NIC.");
        }
        else if(txtphone.getText().trim().isEmpty()){
           lbl_phone.setText("Needed Phone No.");
        }
        else if(txtadd.getText().trim().isEmpty()){
             lbl_add.setText("Needed Address.");
        }
        else{
        try {
            // TODO add your handling code here:        
            PreparedStatement pst = con.prepareStatement("insert into users values(?,?,?,?,?,?)");
            pst.setString(1, txtno.getText());
            pst.setString(2, txtname.getText());
            pst.setString(3, txtmail.getText());
            pst.setString(4, txtnic.getText());
            pst.setString(5, txtphone.getText());
            pst.setString(6, txtadd.getText());
            
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this,"The user has successfully registered.");
            
              autoID();
              
              txtname.setText("");
              txtmail.setText("");
              txtnic.setText("");
              txtphone.setText("");
              txtadd.setText("");
              txtname.requestFocus(); 
              
            
        } catch (SQLException ex) {
            Logger.getLogger(autoIn.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        }
    }//GEN-LAST:event_addActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        manager_main_page L1 =new manager_main_page();
        L1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void txtaddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddKeyReleased
        // TODO add your handling code here:
         lbl_add.setText("");
    }//GEN-LAST:event_txtaddKeyReleased

    private void txtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtphoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyReleased
        // TODO add your handling code here:
         lbl_phone.setText("");
    }//GEN-LAST:event_txtphoneKeyReleased

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyReleased
        // TODO add your handling code here:
         lbl_nic.setText("");
    }//GEN-LAST:event_txtnicKeyReleased

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void txtmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmailKeyReleased
        // TODO add your handling code here:
         lbl_mail.setText("");
    }//GEN-LAST:event_txtmailKeyReleased

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
         lbl_name.setText("");
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void txtnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoKeyReleased

    private void lbl_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_nameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_nameKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_register_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_register_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_register_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_register_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new manager_register_user().setVisible(true);
        });
    }
    
       public void autoID()
    {
        try {
           //Database Connection
            DB obj=new DB();
                Connection con=obj.connect();
            Statement s = con.createStatement();
            
            ResultSet rs = s.executeQuery("select Max(id) from users");
            rs.next();
            
            rs.getString("Max(id)");
            
            
            if(rs.getString("Max(id)")==null)
            {
                
                txtno.setText("U001");
            }
            else
            {
                Long id = Long.parseLong(rs.getString("Max(id)").substring(2,rs.getString("Max(id)").length()));
                id++;
                txtno.setText("U0" + String.format("%02d", id));
                
                
                
                
            }
         
            
            
        } catch (SQLException ex) {
            Logger.getLogger(autoIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_add;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
